modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="newmountains"
version="1.2.1 Pr"
displayName="New Mountains Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://github.com/KapDEK/Updateurl/blob/main/update.json"
authors="Frosty Peaks"
description='''
New Mountains 1.2.1 Pre-Release 1
'''

[[dependencies.newmountains]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.newmountains]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0]"
    ordering="NONE"
    side="BOTH"



