modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="newmountains"
version="1.2.1-pre2"
displayName="New Mountains Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/new-mountains-mod"
authors="Frosty Peaks"
description='''
New Mountains 1.2.1 Pre-Release 2
'''

[[dependencies.newmountains]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




